server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages
    fallback-to-system-locale: false
#  security:
#    user:
#      name: username
#      password: passw0rd
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled:true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
    defer-datasource-initialization: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Swagger springdoc-ui Configuration
#springdoc:
#  packages-to-scan: com.test.demo
#  default-consumes-media-type: application/json;charset=UTF-8
#  default-produces-media-type: application/json;charset=UTF-8
#  swagger-ui:
#    path: demo-ui.html            # Swagger UI 경로 => localhost:8000/demo-ui.html
#    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
#    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
#  api-docs:
#    path: /api-docs/json
#    groups:
#      enabled: true
#  cache:
#    disabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"


